package com.i_africa.shiftcalenderobajana.utils.shift_calendar

import android.graphics.Color
import com.i_africa.shiftcalenderobajana.databinding.ActivityCustomShiftBinding

private val TAG = ReverseTextAndBackgroundColor::class.simpleName
object ReverseTextAndBackgroundColor {

     fun reverseTextAndBackgroundColor(binding: ActivityCustomShiftBinding) {
        binding.one.setTextColor(Color.parseColor("#000000"))
        binding.two.setTextColor(Color.parseColor("#000000"))
        binding.three.setTextColor(Color.parseColor("#000000"))
        binding.four.setTextColor(Color.parseColor("#000000"))
        binding.five.setTextColor(Color.parseColor("#000000"))
        binding.six.setTextColor(Color.parseColor("#000000"))
        binding.seven.setTextColor(Color.parseColor("#000000"))
        binding.eight.setTextColor(Color.parseColor("#000000"))
        binding.nine.setTextColor(Color.parseColor("#000000"))
        binding.ten.setTextColor(Color.parseColor("#000000"))
        binding.eleven.setTextColor(Color.parseColor("#000000"))
        binding.twelve.setTextColor(Color.parseColor("#000000"))
        binding.thirteen.setTextColor(Color.parseColor("#000000"))
        binding.fourteen.setTextColor(Color.parseColor("#000000"))
        binding.fifteen.setTextColor(Color.parseColor("#000000"))
        binding.sixteen.setTextColor(Color.parseColor("#000000"))
        binding.seventeen.setTextColor(Color.parseColor("#000000"))
        binding.eighteen.setTextColor(Color.parseColor("#000000"))
        binding.nineteen.setTextColor(Color.parseColor("#000000"))
        binding.twenty.setTextColor(Color.parseColor("#000000"))
        binding.twentyone.setTextColor(Color.parseColor("#000000"))
        binding.twentytwo.setTextColor(Color.parseColor("#000000"))
        binding.twentythree.setTextColor(Color.parseColor("#000000"))
        binding.twentyfour.setTextColor(Color.parseColor("#000000"))
        binding.twentyfive.setTextColor(Color.parseColor("#000000"))
        binding.twentysix.setTextColor(Color.parseColor("#000000"))
        binding.twentyseven.setTextColor(Color.parseColor("#000000"))
        binding.twentyeight.setTextColor(Color.parseColor("#000000"))
        binding.twentynine.setTextColor(Color.parseColor("#000000"))
        binding.thirty.setTextColor(Color.parseColor("#000000"))
        binding.thirtyone.setTextColor(Color.parseColor("#000000"))
        binding.thirtytwo.setTextColor(Color.parseColor("#000000"))
        binding.thirtythree.setTextColor(Color.parseColor("#000000"))
        binding.thirtyfour.setTextColor(Color.parseColor("#000000"))
        binding.thirtyfive.setTextColor(Color.parseColor("#000000"))
        binding.thirtysix.setTextColor(Color.parseColor("#000000"))
        binding.thirtyseven.setTextColor(Color.parseColor("#000000"))

        reverseTextBackgroundColor(binding)
    }

    private fun reverseTextBackgroundColor(binding: ActivityCustomShiftBinding) {
       binding.one.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.two.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.three.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.four.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.five.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.six.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.seven.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.eight.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.nine.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.ten.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.eleven.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twelve.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirteen.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.fourteen.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.fifteen.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.sixteen.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.seventeen.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.eighteen.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.nineteen.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twenty.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentyone.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentytwo.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentythree.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentyfour.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentyfive.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentysix.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentyseven.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentyeight.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.twentynine.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirty.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirtyone.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirtytwo.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirtythree.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirtyfour.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirtyfive.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirtysix.setBackgroundColor(Color.parseColor("#FFFFFF"))
       binding.thirtyseven.setBackgroundColor(Color.parseColor("#FFFFFF"))
    }
}